upstream api_service {

    hash $stream_id consistent;

    server woolf:9180;  # Use the service name as a hostname
    keepalive 300;       # Enable keepalive connections to upstream servers


}

upstream grpc_service {

    #hash $stream_id consistent;
    hash 'static_value' consistent;

    server woolf:9181;  # Use the service name as a hostname
    keepalive 300;       # Enable keepalive connections to upstream servers

    
}

server {
    listen 9180;

    location / {

        # Extract the Woolf-Partition-ID header for consistent routing
        set $stream_id $http_woolf-stream;

        # Fallback if the Woolf-Partition-ID header is missing
        if ($stream_id = "") {
            set $stream_id $remote_addr;  # Consider adding a more unique identifier if possible
        }

        proxy_pass http://api_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 9181;
    http2 on;
    client_max_body_size 100M;

    location / {
         # Extract the Woolf-Partition-ID header for consistent routing
        set $stream_id $http_woolf-stream;

        # Fallback if the Woolf-Partition-ID header is missing
        if ($stream_id = "") {
            set $stream_id $remote_addr;  # Consider adding a more unique identifier if possible
        }


        grpc_pass grpc://grpc_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Define a log format that includes the Woolf-Partition-ID header
log_format custom_format '$remote_addr - $remote_user [$time_local] $request $status $body_bytes_sent $http_referer $http_user_agent woolf-stream-id : $stream_id';

# Apply this log format to the access log
access_log /var/log/nginx/access.log custom_format;
error_log /var/log/nginx/error.log debug;

resolver 127.0.0.11 valid=10s;
