// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: services.proto

package grpc

import (
	context "context"
	models "github.com/fgrzl/woolf/pkg/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Woolf_CreatePartition_FullMethodName  = "/woolf.Woolf/CreatePartition"
	Woolf_GetStatus_FullMethodName        = "/woolf.Woolf/GetStatus"
	Woolf_GetSpaces_FullMethodName        = "/woolf.Woolf/GetSpaces"
	Woolf_GetPartitions_FullMethodName    = "/woolf.Woolf/GetPartitions"
	Woolf_Produce_FullMethodName          = "/woolf.Woolf/Produce"
	Woolf_ConsumeSpace_FullMethodName     = "/woolf.Woolf/ConsumeSpace"
	Woolf_ConsumePartition_FullMethodName = "/woolf.Woolf/ConsumePartition"
	Woolf_Peek_FullMethodName             = "/woolf.Woolf/Peek"
	Woolf_Merge_FullMethodName            = "/woolf.Woolf/Merge"
	Woolf_Prune_FullMethodName            = "/woolf.Woolf/Prune"
	Woolf_Rebuild_FullMethodName          = "/woolf.Woolf/Rebuild"
)

// WoolfClient is the client API for Woolf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PartitionServices is the service definition for the stream-related operations.
type WoolfClient interface {
	CreatePartition(ctx context.Context, in *models.CreatePartitionRequest, opts ...grpc.CallOption) (*models.StatusResponse, error)
	GetStatus(ctx context.Context, in *models.GetStatusRequest, opts ...grpc.CallOption) (*models.StatusResponse, error)
	// Get the spaces
	GetSpaces(ctx context.Context, in *models.GetSpacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.SpaceDescriptor], error)
	// Get the streams
	GetPartitions(ctx context.Context, in *models.GetPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PartitionDescriptor], error)
	// Produce entries
	Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[models.Entry, models.PageDescriptor], error)
	// Consume entries in a space.
	ConsumeSpace(ctx context.Context, in *models.ConsumeSpaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.EntryEnvelope], error)
	// Consume entries in a stream
	ConsumePartition(ctx context.Context, in *models.ConsumePartitionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.EntryEnvelope], error)
	// Peek at the last entry in a stream
	Peek(ctx context.Context, in *models.PeekRequest, opts ...grpc.CallOption) (*models.EntryEnvelope, error)
	// Merge pages from a stream into the next tier
	Merge(ctx context.Context, in *models.MergeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PageDescriptor], error)
	// Prune obsolete pages from a tier
	Prune(ctx context.Context, in *models.PruneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PageDescriptor], error)
	// Rebuild the manifest for a tier
	Rebuild(ctx context.Context, in *models.RebuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.RebuildResponse], error)
}

type woolfClient struct {
	cc grpc.ClientConnInterface
}

func NewWoolfClient(cc grpc.ClientConnInterface) WoolfClient {
	return &woolfClient{cc}
}

func (c *woolfClient) CreatePartition(ctx context.Context, in *models.CreatePartitionRequest, opts ...grpc.CallOption) (*models.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.StatusResponse)
	err := c.cc.Invoke(ctx, Woolf_CreatePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *woolfClient) GetStatus(ctx context.Context, in *models.GetStatusRequest, opts ...grpc.CallOption) (*models.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.StatusResponse)
	err := c.cc.Invoke(ctx, Woolf_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *woolfClient) GetSpaces(ctx context.Context, in *models.GetSpacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.SpaceDescriptor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[0], Woolf_GetSpaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.GetSpacesRequest, models.SpaceDescriptor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_GetSpacesClient = grpc.ServerStreamingClient[models.SpaceDescriptor]

func (c *woolfClient) GetPartitions(ctx context.Context, in *models.GetPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PartitionDescriptor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[1], Woolf_GetPartitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.GetPartitionsRequest, models.PartitionDescriptor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_GetPartitionsClient = grpc.ServerStreamingClient[models.PartitionDescriptor]

func (c *woolfClient) Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[models.Entry, models.PageDescriptor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[2], Woolf_Produce_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.Entry, models.PageDescriptor]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ProduceClient = grpc.BidiStreamingClient[models.Entry, models.PageDescriptor]

func (c *woolfClient) ConsumeSpace(ctx context.Context, in *models.ConsumeSpaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.EntryEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[3], Woolf_ConsumeSpace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.ConsumeSpaceRequest, models.EntryEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ConsumeSpaceClient = grpc.ServerStreamingClient[models.EntryEnvelope]

func (c *woolfClient) ConsumePartition(ctx context.Context, in *models.ConsumePartitionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.EntryEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[4], Woolf_ConsumePartition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.ConsumePartitionRequest, models.EntryEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ConsumePartitionClient = grpc.ServerStreamingClient[models.EntryEnvelope]

func (c *woolfClient) Peek(ctx context.Context, in *models.PeekRequest, opts ...grpc.CallOption) (*models.EntryEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.EntryEnvelope)
	err := c.cc.Invoke(ctx, Woolf_Peek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *woolfClient) Merge(ctx context.Context, in *models.MergeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PageDescriptor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[5], Woolf_Merge_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.MergeRequest, models.PageDescriptor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_MergeClient = grpc.ServerStreamingClient[models.PageDescriptor]

func (c *woolfClient) Prune(ctx context.Context, in *models.PruneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.PageDescriptor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[6], Woolf_Prune_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.PruneRequest, models.PageDescriptor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_PruneClient = grpc.ServerStreamingClient[models.PageDescriptor]

func (c *woolfClient) Rebuild(ctx context.Context, in *models.RebuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[models.RebuildResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Woolf_ServiceDesc.Streams[7], Woolf_Rebuild_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.RebuildRequest, models.RebuildResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_RebuildClient = grpc.ServerStreamingClient[models.RebuildResponse]

// WoolfServer is the server API for Woolf service.
// All implementations must embed UnimplementedWoolfServer
// for forward compatibility.
//
// PartitionServices is the service definition for the stream-related operations.
type WoolfServer interface {
	CreatePartition(context.Context, *models.CreatePartitionRequest) (*models.StatusResponse, error)
	GetStatus(context.Context, *models.GetStatusRequest) (*models.StatusResponse, error)
	// Get the spaces
	GetSpaces(*models.GetSpacesRequest, grpc.ServerStreamingServer[models.SpaceDescriptor]) error
	// Get the streams
	GetPartitions(*models.GetPartitionsRequest, grpc.ServerStreamingServer[models.PartitionDescriptor]) error
	// Produce entries
	Produce(grpc.BidiStreamingServer[models.Entry, models.PageDescriptor]) error
	// Consume entries in a space.
	ConsumeSpace(*models.ConsumeSpaceRequest, grpc.ServerStreamingServer[models.EntryEnvelope]) error
	// Consume entries in a stream
	ConsumePartition(*models.ConsumePartitionRequest, grpc.ServerStreamingServer[models.EntryEnvelope]) error
	// Peek at the last entry in a stream
	Peek(context.Context, *models.PeekRequest) (*models.EntryEnvelope, error)
	// Merge pages from a stream into the next tier
	Merge(*models.MergeRequest, grpc.ServerStreamingServer[models.PageDescriptor]) error
	// Prune obsolete pages from a tier
	Prune(*models.PruneRequest, grpc.ServerStreamingServer[models.PageDescriptor]) error
	// Rebuild the manifest for a tier
	Rebuild(*models.RebuildRequest, grpc.ServerStreamingServer[models.RebuildResponse]) error
	mustEmbedUnimplementedWoolfServer()
}

// UnimplementedWoolfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWoolfServer struct{}

func (UnimplementedWoolfServer) CreatePartition(context.Context, *models.CreatePartitionRequest) (*models.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartition not implemented")
}
func (UnimplementedWoolfServer) GetStatus(context.Context, *models.GetStatusRequest) (*models.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedWoolfServer) GetSpaces(*models.GetSpacesRequest, grpc.ServerStreamingServer[models.SpaceDescriptor]) error {
	return status.Errorf(codes.Unimplemented, "method GetSpaces not implemented")
}
func (UnimplementedWoolfServer) GetPartitions(*models.GetPartitionsRequest, grpc.ServerStreamingServer[models.PartitionDescriptor]) error {
	return status.Errorf(codes.Unimplemented, "method GetPartitions not implemented")
}
func (UnimplementedWoolfServer) Produce(grpc.BidiStreamingServer[models.Entry, models.PageDescriptor]) error {
	return status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedWoolfServer) ConsumeSpace(*models.ConsumeSpaceRequest, grpc.ServerStreamingServer[models.EntryEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeSpace not implemented")
}
func (UnimplementedWoolfServer) ConsumePartition(*models.ConsumePartitionRequest, grpc.ServerStreamingServer[models.EntryEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method ConsumePartition not implemented")
}
func (UnimplementedWoolfServer) Peek(context.Context, *models.PeekRequest) (*models.EntryEnvelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Peek not implemented")
}
func (UnimplementedWoolfServer) Merge(*models.MergeRequest, grpc.ServerStreamingServer[models.PageDescriptor]) error {
	return status.Errorf(codes.Unimplemented, "method Merge not implemented")
}
func (UnimplementedWoolfServer) Prune(*models.PruneRequest, grpc.ServerStreamingServer[models.PageDescriptor]) error {
	return status.Errorf(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedWoolfServer) Rebuild(*models.RebuildRequest, grpc.ServerStreamingServer[models.RebuildResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Rebuild not implemented")
}
func (UnimplementedWoolfServer) mustEmbedUnimplementedWoolfServer() {}
func (UnimplementedWoolfServer) testEmbeddedByValue()               {}

// UnsafeWoolfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WoolfServer will
// result in compilation errors.
type UnsafeWoolfServer interface {
	mustEmbedUnimplementedWoolfServer()
}

func RegisterWoolfServer(s grpc.ServiceRegistrar, srv WoolfServer) {
	// If the following call pancis, it indicates UnimplementedWoolfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Woolf_ServiceDesc, srv)
}

func _Woolf_CreatePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WoolfServer).CreatePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Woolf_CreatePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WoolfServer).CreatePartition(ctx, req.(*models.CreatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Woolf_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WoolfServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Woolf_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WoolfServer).GetStatus(ctx, req.(*models.GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Woolf_GetSpaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.GetSpacesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).GetSpaces(m, &grpc.GenericServerStream[models.GetSpacesRequest, models.SpaceDescriptor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_GetSpacesServer = grpc.ServerStreamingServer[models.SpaceDescriptor]

func _Woolf_GetPartitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.GetPartitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).GetPartitions(m, &grpc.GenericServerStream[models.GetPartitionsRequest, models.PartitionDescriptor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_GetPartitionsServer = grpc.ServerStreamingServer[models.PartitionDescriptor]

func _Woolf_Produce_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WoolfServer).Produce(&grpc.GenericServerStream[models.Entry, models.PageDescriptor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ProduceServer = grpc.BidiStreamingServer[models.Entry, models.PageDescriptor]

func _Woolf_ConsumeSpace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.ConsumeSpaceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).ConsumeSpace(m, &grpc.GenericServerStream[models.ConsumeSpaceRequest, models.EntryEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ConsumeSpaceServer = grpc.ServerStreamingServer[models.EntryEnvelope]

func _Woolf_ConsumePartition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.ConsumePartitionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).ConsumePartition(m, &grpc.GenericServerStream[models.ConsumePartitionRequest, models.EntryEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_ConsumePartitionServer = grpc.ServerStreamingServer[models.EntryEnvelope]

func _Woolf_Peek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.PeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WoolfServer).Peek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Woolf_Peek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WoolfServer).Peek(ctx, req.(*models.PeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Woolf_Merge_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.MergeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).Merge(m, &grpc.GenericServerStream[models.MergeRequest, models.PageDescriptor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_MergeServer = grpc.ServerStreamingServer[models.PageDescriptor]

func _Woolf_Prune_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.PruneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).Prune(m, &grpc.GenericServerStream[models.PruneRequest, models.PageDescriptor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_PruneServer = grpc.ServerStreamingServer[models.PageDescriptor]

func _Woolf_Rebuild_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(models.RebuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WoolfServer).Rebuild(m, &grpc.GenericServerStream[models.RebuildRequest, models.RebuildResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Woolf_RebuildServer = grpc.ServerStreamingServer[models.RebuildResponse]

// Woolf_ServiceDesc is the grpc.ServiceDesc for Woolf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Woolf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woolf.Woolf",
	HandlerType: (*WoolfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePartition",
			Handler:    _Woolf_CreatePartition_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Woolf_GetStatus_Handler,
		},
		{
			MethodName: "Peek",
			Handler:    _Woolf_Peek_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSpaces",
			Handler:       _Woolf_GetSpaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPartitions",
			Handler:       _Woolf_GetPartitions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Produce",
			Handler:       _Woolf_Produce_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConsumeSpace",
			Handler:       _Woolf_ConsumeSpace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConsumePartition",
			Handler:       _Woolf_ConsumePartition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Merge",
			Handler:       _Woolf_Merge_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Prune",
			Handler:       _Woolf_Prune_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Rebuild",
			Handler:       _Woolf_Rebuild_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}
